/**
 * ShopiQ demo catalogue.
 *
 * Specifications are stored as typed key/value pairs, never as presentation
 * text — the Phase 2 AI agent has to be able to answer "under 2 kg with at
 * least 16 GB of RAM" by filtering on these values.
 *
 * Prices are plain numbers in INR (79999, not "₹79,999").
 */

export const SPEC_LABELS = {
  processor:          { label: 'Processor' },
  ram_gb:             { label: 'Memory', unit: 'GB' },
  storage_gb:         { label: 'Storage', unit: 'GB' },
  storage_type:       { label: 'Storage type' },
  gpu:                { label: 'Graphics' },
  display_size:       { label: 'Display size', unit: 'in' },
  display_resolution: { label: 'Resolution' },
  display_type:       { label: 'Display type' },
  refresh_rate_hz:    { label: 'Refresh rate', unit: 'Hz' },
  brightness_nits:    { label: 'Brightness', unit: 'nits' },
  response_time_ms:   { label: 'Response time', unit: 'ms' },
  panel_type:         { label: 'Panel' },
  adjustable_stand:   { label: 'Stand adjustment' },
  weight_kg:          { label: 'Weight', unit: 'kg' },
  weight_g:           { label: 'Weight', unit: 'g' },
  battery_wh:         { label: 'Battery', unit: 'Wh' },
  battery_mah:        { label: 'Battery', unit: 'mAh' },
  battery_hours:      { label: 'Battery life', unit: 'hours' },
  charging_w:         { label: 'Fast charging', unit: 'W' },
  os:                 { label: 'Operating system' },
  ports:              { label: 'Ports' },
  rear_camera_mp:     { label: 'Rear camera', unit: 'MP' },
  front_camera_mp:    { label: 'Front camera', unit: 'MP' },
  water_resistance:   { label: 'Water resistance' },
  type:               { label: 'Type' },
  noise_cancellation: { label: 'Noise cancellation' },
  bluetooth_version:  { label: 'Bluetooth' },
  driver_mm:          { label: 'Drivers', unit: 'mm' },
  mic:                { label: 'Microphone' },
  connection:         { label: 'Connection' },
  layout:             { label: 'Layout' },
  switch_type:        { label: 'Switches' },
  backlight:          { label: 'Backlight' },
  hot_swappable:      { label: 'Hot-swappable' },
  sensor_dpi:         { label: 'Sensor', unit: 'DPI' },
  buttons:            { label: 'Buttons' },
  polling_rate_hz:    { label: 'Polling rate', unit: 'Hz' },
  compatibility:      { label: 'Compatibility' },
  haptics:            { label: 'Haptics' },
  material:           { label: 'Material' },
  sole:               { label: 'Sole' },
  closure:            { label: 'Closure' },
  use_case:           { label: 'Best for' },
  sizes:              { label: 'Sizes' },
  fit:                { label: 'Fit' },
  gsm:                { label: 'Fabric weight', unit: 'GSM' },
  sleeve:             { label: 'Sleeve' },
  care:               { label: 'Care' },
  insulation:         { label: 'Insulation' },
  pockets:            { label: 'Pockets' },
  capacity_l:         { label: 'Capacity', unit: 'L' },
  capacity_ml:        { label: 'Capacity', unit: 'ml' },
  laptop_fit_inch:    { label: 'Fits laptop', unit: 'in' },
  compartments:       { label: 'Compartments' },
  dimensions_cm:      { label: 'Dimensions', unit: 'cm' },
  power_w:            { label: 'Power', unit: 'W' },
  warranty_months:    { label: 'Warranty', unit: 'months' },
  colour:             { label: 'Colour' },
};

/** Order matters: parents must be inserted before their children. */
export const CATEGORIES = [
  { slug: 'electronics', name: 'Electronics', parent: null, sort: 1,
    description: 'Laptops, phones, audio and the screens in between.' },
  { slug: 'gaming', name: 'Gaming', parent: null, sort: 2,
    description: 'Machines, controllers and gear built for play.' },
  { slug: 'fashion', name: 'Fashion', parent: null, sort: 3,
    description: 'Everyday wear that survives an everyday commute.' },
  { slug: 'home', name: 'Home', parent: null, sort: 4,
    description: 'Small upgrades for the desk and the room around it.' },

  { slug: 'laptops', name: 'Laptops', parent: 'electronics', sort: 1,
    description: 'Ultrabooks and workstations for study, work and code.' },
  { slug: 'smartphones', name: 'Smartphones', parent: 'electronics', sort: 2,
    description: 'Flagships and value phones across every budget.' },
  { slug: 'headphones', name: 'Headphones', parent: 'electronics', sort: 3,
    description: 'Over-ear, in-ear and everything with a battery in it.' },
  { slug: 'monitors', name: 'Monitors', parent: 'electronics', sort: 4,
    description: 'Colour-accurate panels and high refresh-rate displays.' },
  { slug: 'keyboards', name: 'Keyboards', parent: 'electronics', sort: 5,
    description: 'Mechanical, low-profile and wireless boards.' },
  { slug: 'mice', name: 'Mice', parent: 'electronics', sort: 6,
    description: 'Precision pointers for work and for aim.' },

  { slug: 'gaming-laptops', name: 'Gaming Laptops', parent: 'gaming', sort: 1,
    description: 'Discrete graphics, high refresh panels, real cooling.' },
  { slug: 'controllers', name: 'Controllers', parent: 'gaming', sort: 2,
    description: 'Gamepads for PC, console and mobile.' },
  { slug: 'gaming-headsets', name: 'Gaming Headsets', parent: 'gaming', sort: 3,
    description: 'Low-latency audio with a microphone attached.' },
  { slug: 'gaming-accessories', name: 'Gaming Accessories', parent: 'gaming', sort: 4,
    description: 'Pads, stands, hubs and the rest of the desk.' },

  { slug: 'shoes', name: 'Shoes', parent: 'fashion', sort: 1,
    description: 'Running, training and everyday sneakers.' },
  { slug: 't-shirts', name: 'T-Shirts', parent: 'fashion', sort: 2,
    description: 'Cotton basics and technical tees.' },
  { slug: 'jackets', name: 'Jackets', parent: 'fashion', sort: 3,
    description: 'Windproof shells, puffers and overshirts.' },
  { slug: 'bags', name: 'Bags', parent: 'fashion', sort: 4,
    description: 'Backpacks, slings and laptop sleeves.' },

  { slug: 'home-accessories', name: 'Home Accessories', parent: 'home', sort: 1,
    description: 'Desk lamps, chargers, bottles and small comforts.' },
];

const p = (o) => o;

export const PRODUCTS = [
  // ---------------------------------------------------------------- laptops
  p({
    cat: 'laptops', brand: 'ASUS', name: 'Zenbook 14 OLED (2025)', sku: 'SQ-LAP-0001',
    price: 86990, mrp: 104990, rating: 4.6, reviews: 412, featured: true, stock: 18,
    tags: ['ultrabook', 'oled', 'thin and light', 'student', 'office'],
    short: 'A 1.2 kg OLED ultrabook that runs cool and lasts a full working day.',
    desc: 'The Zenbook 14 OLED pairs a 3K 120 Hz OLED panel with Intel Core Ultra silicon in a 1.2 kg magnesium-aluminium chassis. It is built for people who carry a laptop every day and occasionally need it to compile something serious.',
    specs: { processor: 'Intel Core Ultra 7 155H', ram_gb: 16, storage_gb: 1024, storage_type: 'NVMe SSD',
      gpu: 'Intel Arc integrated', display_size: 14, display_resolution: '2880 x 1800', display_type: 'OLED',
      refresh_rate_hz: 120, weight_kg: 1.2, battery_wh: 75, os: 'Windows 11 Home',
      ports: '2x Thunderbolt 4, USB-A, HDMI 2.1, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'Apple', name: 'MacBook Air 13-inch M4', sku: 'SQ-LAP-0002',
    price: 99900, mrp: null, rating: 4.8, reviews: 1942, featured: true, stock: 24,
    tags: ['macbook', 'ultrabook', 'fanless', 'student', 'developer'],
    short: 'Silent, 1.24 kg, and good for well over a day of real work.',
    desc: 'The M4 MacBook Air is fanless, which means it is completely silent under load until the very heaviest exports. For web development, writing and design it is close to the ideal portable machine.',
    specs: { processor: 'Apple M4 (10-core)', ram_gb: 16, storage_gb: 256, storage_type: 'NVMe SSD',
      gpu: 'Apple M4 10-core GPU', display_size: 13.6, display_resolution: '2560 x 1664',
      display_type: 'Liquid Retina IPS', refresh_rate_hz: 60, weight_kg: 1.24, battery_wh: 53.8,
      os: 'macOS', ports: '2x Thunderbolt 4, MagSafe 3, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'Lenovo', name: 'IdeaPad Slim 5 14-inch', sku: 'SQ-LAP-0003',
    price: 58499, mrp: 67990, rating: 4.4, reviews: 671, featured: true, stock: 31,
    tags: ['budget', 'student', 'office', 'thin and light'],
    short: 'The sensible 14-inch pick under ₹60,000 — 16 GB RAM as standard.',
    desc: 'A well-built aluminium 14-inch with a bright IPS panel and 16 GB of memory at a price where most rivals still ship 8 GB. Good for coursework, browsers with too many tabs, and light photo editing.',
    specs: { processor: 'AMD Ryzen 5 8645HS', ram_gb: 16, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'AMD Radeon 760M integrated', display_size: 14, display_resolution: '1920 x 1200',
      display_type: 'IPS', refresh_rate_hz: 60, weight_kg: 1.46, battery_wh: 57,
      os: 'Windows 11 Home', ports: 'USB-C, 2x USB-A, HDMI, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'HP', name: 'Pavilion Aero 13', sku: 'SQ-LAP-0004',
    price: 72990, mrp: 84999, rating: 4.3, reviews: 288, featured: false, stock: 12,
    tags: ['ultrabook', 'lightweight', 'magnesium', 'travel'],
    short: 'Under a kilogram, with a 16:10 screen that is brighter than it needs to be.',
    desc: 'At 970 g the Pavilion Aero is one of the lightest Windows laptops you can buy without moving into business pricing. The magnesium chassis keeps it rigid despite the weight.',
    specs: { processor: 'AMD Ryzen 7 8840U', ram_gb: 16, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'AMD Radeon 780M integrated', display_size: 13.3, display_resolution: '2560 x 1600',
      display_type: 'IPS', refresh_rate_hz: 60, weight_kg: 0.97, battery_wh: 43,
      os: 'Windows 11 Home', ports: 'USB-C, 2x USB-A, HDMI, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'Dell', name: 'Inspiron 15 Business', sku: 'SQ-LAP-0005',
    price: 51990, mrp: 62990, rating: 4.1, reviews: 934, featured: false, stock: 4,
    tags: ['budget', 'office', 'numpad', '15 inch'],
    short: 'A plain, reliable 15-inch with a numpad and a big battery.',
    desc: 'Not exciting, but it has every port you actually use, a full numeric keypad and a battery that holds up through a working day of documents and video calls.',
    specs: { processor: 'Intel Core i5-1334U', ram_gb: 16, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'Intel Iris Xe integrated', display_size: 15.6, display_resolution: '1920 x 1080',
      display_type: 'IPS', refresh_rate_hz: 60, weight_kg: 1.65, battery_wh: 54,
      os: 'Windows 11 Home', ports: 'USB-C, 2x USB-A, HDMI, SD, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'Apple', name: 'MacBook Pro 14-inch M4 Pro', sku: 'SQ-LAP-0006',
    price: 199900, mrp: 219900, rating: 4.9, reviews: 806, featured: false, stock: 7,
    tags: ['macbook', 'pro', 'video editing', 'developer', 'xdr'],
    short: 'For sustained heavy work — compiling, colour grading, large builds.',
    desc: 'The M4 Pro adds real sustained performance and a Liquid Retina XDR panel with 1600 nits of peak brightness. This is the machine you buy when the laptop is the whole workstation.',
    specs: { processor: 'Apple M4 Pro (12-core)', ram_gb: 24, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'Apple M4 Pro 16-core GPU', display_size: 14.2, display_resolution: '3024 x 1964',
      display_type: 'Liquid Retina XDR', refresh_rate_hz: 120, brightness_nits: 1600,
      weight_kg: 1.6, battery_wh: 72.4, os: 'macOS',
      ports: '3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'laptops', brand: 'Acer', name: 'Swift Go 14 OLED', sku: 'SQ-LAP-0007',
    price: 64990, mrp: 76999, rating: 4.2, reviews: 341, featured: false, stock: 15,
    tags: ['oled', 'budget', 'thin and light', 'student'],
    short: 'The cheapest way into a proper OLED laptop screen.',
    desc: 'A 14-inch OLED at this price is unusual. Battery life is only average because of it, but for anything visual the contrast is worth the trade.',
    specs: { processor: 'Intel Core Ultra 5 125H', ram_gb: 16, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'Intel Arc integrated', display_size: 14, display_resolution: '2880 x 1800',
      display_type: 'OLED', refresh_rate_hz: 90, weight_kg: 1.32, battery_wh: 65,
      os: 'Windows 11 Home', ports: '2x USB-C, 2x USB-A, HDMI, 3.5mm', warranty_months: 12 },
  }),

  // --------------------------------------------------------- gaming laptops
  p({
    cat: 'gaming-laptops', brand: 'ASUS', name: 'TUF Gaming A15 (2025)', sku: 'SQ-GLP-0001',
    price: 79999, mrp: 89999, rating: 4.6, reviews: 238, featured: true, stock: 12,
    tags: ['gaming', 'rtx 4060', 'ryzen', '144hz', 'programming'],
    short: 'A 15.6" 144 Hz machine built for long compiles and long sessions alike.',
    desc: 'Ryzen 7, RTX 4060 and 32 GB of memory in a military-grade chassis. The 32 GB is the part that matters if you are running containers and a game on the same machine.',
    specs: { processor: 'AMD Ryzen 7 8845HS', ram_gb: 32, storage_gb: 1024, storage_type: 'NVMe SSD',
      gpu: 'NVIDIA RTX 4060 8 GB', display_size: 15.6, display_resolution: '1920 x 1080',
      display_type: 'IPS', refresh_rate_hz: 144, weight_kg: 2.2, battery_wh: 90,
      os: 'Windows 11 Home', ports: '2x USB-C, 2x USB-A, HDMI 2.1, RJ45, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'gaming-laptops', brand: 'Lenovo', name: 'Legion Pro 5 16-inch', sku: 'SQ-GLP-0002',
    price: 149990, mrp: 179990, rating: 4.7, reviews: 319, featured: true, stock: 6,
    tags: ['gaming', 'rtx 4070', '240hz', 'wqxga', 'high end'],
    short: 'RTX 4070 behind a 16-inch 240 Hz WQXGA panel.',
    desc: 'The Legion Pro 5 is the one to buy if the display matters as much as the frame rate. 240 Hz at 2560x1600 is a genuinely different experience from 1080p144.',
    specs: { processor: 'Intel Core i7-14650HX', ram_gb: 16, storage_gb: 1024, storage_type: 'NVMe SSD',
      gpu: 'NVIDIA RTX 4070 8 GB', display_size: 16, display_resolution: '2560 x 1600',
      display_type: 'IPS', refresh_rate_hz: 240, weight_kg: 2.5, battery_wh: 80,
      os: 'Windows 11 Home', ports: '2x USB-C, 3x USB-A, HDMI 2.1, RJ45, 3.5mm', warranty_months: 24 },
  }),
  p({
    cat: 'gaming-laptops', brand: 'HP', name: 'Victus 15 RTX 4050', sku: 'SQ-GLP-0003',
    price: 67990, mrp: 82999, rating: 4.2, reviews: 1128, featured: false, stock: 22,
    tags: ['gaming', 'budget', 'rtx 4050', '144hz', 'entry level'],
    short: 'Entry-level discrete graphics without an entry-level screen.',
    desc: 'The RTX 4050 handles 1080p at high settings in most current titles. A sensible first gaming laptop that also does coursework without complaint.',
    specs: { processor: 'AMD Ryzen 5 8645HS', ram_gb: 16, storage_gb: 512, storage_type: 'NVMe SSD',
      gpu: 'NVIDIA RTX 4050 6 GB', display_size: 15.6, display_resolution: '1920 x 1080',
      display_type: 'IPS', refresh_rate_hz: 144, weight_kg: 2.29, battery_wh: 70,
      os: 'Windows 11 Home', ports: 'USB-C, 2x USB-A, HDMI 2.1, RJ45, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'gaming-laptops', brand: 'ASUS', name: 'ROG Zephyrus G14 (2025)', sku: 'SQ-GLP-0004',
    price: 164990, mrp: 189990, rating: 4.8, reviews: 452, featured: false, stock: 5,
    tags: ['gaming', 'portable', 'oled', 'rtx 4070', 'premium'],
    short: 'A 1.5 kg gaming laptop with an OLED panel — the portable one.',
    desc: 'The G14 is the answer to "I want to game but I also have to carry this thing every day". 1.5 kg with an RTX 4070 and a 120 Hz OLED display.',
    specs: { processor: 'AMD Ryzen 9 8945HS', ram_gb: 32, storage_gb: 1024, storage_type: 'NVMe SSD',
      gpu: 'NVIDIA RTX 4070 8 GB', display_size: 14, display_resolution: '2880 x 1800',
      display_type: 'OLED', refresh_rate_hz: 120, weight_kg: 1.5, battery_wh: 73,
      os: 'Windows 11 Home', ports: '2x USB-C, 2x USB-A, HDMI 2.1, 3.5mm', warranty_months: 12 },
  }),
  p({
    cat: 'gaming-laptops', brand: 'MSI', name: 'Katana 15 RTX 4060', sku: 'SQ-GLP-0005',
    price: 89990, mrp: 109990, rating: 4.3, reviews: 507, featured: false, stock: 0,
    tags: ['gaming', 'rtx 4060', '144hz', 'intel'],
    short: 'RTX 4060 performance at the lower end of RTX 4060 pricing.',
    desc: 'The Katana trades chassis polish for raw components. If you care about frames per rupee more than about the finish, this is a strong pick.',
    specs: { processor: 'Intel Core i7-13620H', ram_gb: 16, storage_gb: 1024, storage_type: 'NVMe SSD',
      gpu: 'NVIDIA RTX 4060 8 GB', display_size: 15.6, display_resolution: '1920 x 1080',
      display_type: 'IPS', refresh_rate_hz: 144, weight_kg: 2.25, battery_wh: 53,
      os: 'Windows 11 Home', ports: 'USB-C, 3x USB-A, HDMI 2.1, RJ45, 3.5mm', warranty_months: 12 },
  }),

  // ----------------------------------------------------------- smartphones
  p({
    cat: 'smartphones', brand: 'Samsung', name: 'Galaxy S25 128 GB', sku: 'SQ-PHN-0001',
    price: 74999, mrp: 79999, rating: 4.7, reviews: 3108, featured: true, stock: 40,
    tags: ['flagship', 'android', 'amoled', 'camera'],
    short: 'A compact flagship that still fits in one hand.',
    desc: 'The S25 keeps the 6.2-inch size while moving to a brighter LTPO panel and a meaningfully better night mode. Seven years of OS updates is the quiet headline.',
    specs: { display_size: 6.2, display_resolution: '2340 x 1080', display_type: 'Dynamic AMOLED 2X',
      refresh_rate_hz: 120, brightness_nits: 2600, processor: 'Snapdragon 8 Elite', ram_gb: 12,
      storage_gb: 128, rear_camera_mp: 50, front_camera_mp: 12, battery_mah: 4000, charging_w: 25,
      os: 'Android 15', weight_g: 162, water_resistance: 'IP68', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'Apple', name: 'iPhone 16 128 GB', sku: 'SQ-PHN-0002',
    price: 79900, mrp: null, rating: 4.8, reviews: 5412, featured: true, stock: 33,
    tags: ['flagship', 'ios', 'camera', 'oled'],
    short: 'The default answer, and still hard to argue with.',
    desc: 'A18 silicon, a much-improved main camera and the Action button moved down to the standard model. Battery life is the biggest year-on-year gain.',
    specs: { display_size: 6.1, display_resolution: '2556 x 1179', display_type: 'Super Retina XDR OLED',
      refresh_rate_hz: 60, brightness_nits: 2000, processor: 'Apple A18', ram_gb: 8, storage_gb: 128,
      rear_camera_mp: 48, front_camera_mp: 12, battery_mah: 3561, charging_w: 20, os: 'iOS 18',
      weight_g: 170, water_resistance: 'IP68', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'Samsung', name: 'Galaxy A56 5G', sku: 'SQ-PHN-0003',
    price: 34999, mrp: 40999, rating: 4.4, reviews: 1776, featured: false, stock: 55,
    tags: ['mid range', 'android', 'amoled', 'value'],
    short: 'The mid-range phone that gets the screen and updates right.',
    desc: 'A 120 Hz AMOLED and four years of OS updates at ₹35,000. The camera is good in daylight and merely acceptable at night, which is the honest trade at this price.',
    specs: { display_size: 6.7, display_resolution: '2340 x 1080', display_type: 'Super AMOLED',
      refresh_rate_hz: 120, brightness_nits: 1200, processor: 'Exynos 1580', ram_gb: 8, storage_gb: 128,
      rear_camera_mp: 50, front_camera_mp: 12, battery_mah: 5000, charging_w: 45, os: 'Android 15',
      weight_g: 198, water_resistance: 'IP67', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'OnePlus', name: 'OnePlus 13R', sku: 'SQ-PHN-0004',
    price: 42999, mrp: 47999, rating: 4.5, reviews: 2204, featured: false, stock: 27,
    tags: ['performance', 'android', 'fast charging', 'battery'],
    short: 'Flagship-adjacent performance and a 6000 mAh battery.',
    desc: 'The 13R runs last year\'s flagship chip, which in practice means it is faster than most phones costing more. The battery is the real reason to buy it.',
    specs: { display_size: 6.78, display_resolution: '2780 x 1264', display_type: 'LTPO AMOLED',
      refresh_rate_hz: 120, brightness_nits: 4500, processor: 'Snapdragon 8 Gen 3', ram_gb: 12,
      storage_gb: 256, rear_camera_mp: 50, front_camera_mp: 16, battery_mah: 6000, charging_w: 80,
      os: 'Android 15', weight_g: 206, water_resistance: 'IP65', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'Google', name: 'Pixel 9a', sku: 'SQ-PHN-0005',
    price: 49999, mrp: 54999, rating: 4.6, reviews: 1102, featured: false, stock: 19,
    tags: ['camera', 'android', 'clean software', 'value flagship'],
    short: 'The best point-and-shoot camera under ₹50,000.',
    desc: 'Google\'s computational photography does more with a smaller sensor than most rivals manage with a bigger one. Seven years of updates, and no preinstalled clutter.',
    specs: { display_size: 6.3, display_resolution: '2424 x 1080', display_type: 'Actua OLED',
      refresh_rate_hz: 120, brightness_nits: 2700, processor: 'Google Tensor G4', ram_gb: 8,
      storage_gb: 128, rear_camera_mp: 48, front_camera_mp: 13, battery_mah: 5100, charging_w: 23,
      os: 'Android 15', weight_g: 186, water_resistance: 'IP68', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'Xiaomi', name: 'Redmi Note 14 Pro+', sku: 'SQ-PHN-0006',
    price: 29999, mrp: 33999, rating: 4.3, reviews: 4881, featured: false, stock: 62,
    tags: ['budget', 'android', 'fast charging', 'big battery'],
    short: '120 W charging and a 200 MP sensor for under ₹30,000.',
    desc: 'Charges from flat to full in about twenty minutes. The 200 MP camera is more useful for cropping than for outright quality, but daylight results are good.',
    specs: { display_size: 6.67, display_resolution: '2712 x 1220', display_type: 'AMOLED',
      refresh_rate_hz: 120, brightness_nits: 3000, processor: 'Snapdragon 7s Gen 3', ram_gb: 8,
      storage_gb: 256, rear_camera_mp: 200, front_camera_mp: 20, battery_mah: 5110, charging_w: 120,
      os: 'Android 14', weight_g: 210, water_resistance: 'IP68', warranty_months: 12 },
  }),
  p({
    cat: 'smartphones', brand: 'Motorola', name: 'Edge 60 Fusion', sku: 'SQ-PHN-0007',
    price: 22999, mrp: 26999, rating: 4.1, reviews: 903, featured: false, stock: 3,
    tags: ['budget', 'android', 'curved display', 'clean software'],
    short: 'Near-stock Android on a curved pOLED panel at a budget price.',
    desc: 'Motorola\'s software stays close to stock Android, which keeps this phone feeling quick for longer than its chip suggests it should.',
    specs: { display_size: 6.7, display_resolution: '2712 x 1220', display_type: 'pOLED',
      refresh_rate_hz: 120, brightness_nits: 1600, processor: 'Dimensity 7300', ram_gb: 8,
      storage_gb: 128, rear_camera_mp: 50, front_camera_mp: 32, battery_mah: 5500, charging_w: 68,
      os: 'Android 15', weight_g: 180, water_resistance: 'IP68', warranty_months: 12 },
  }),

  // ------------------------------------------------------------ headphones
  p({
    cat: 'headphones', brand: 'Sony', name: 'WH-1000XM6', sku: 'SQ-AUD-0001',
    price: 34990, mrp: 39990, rating: 4.8, reviews: 2645, featured: true, stock: 14,
    tags: ['anc', 'over ear', 'travel', 'premium', 'wireless'],
    short: 'The noise cancelling benchmark, still.',
    desc: 'Nothing else cancels low-frequency noise this well. Thirty hours with ANC on means a return flight on one charge, and the folding hinge is back.',
    specs: { type: 'Over-ear', noise_cancellation: 'Adaptive ANC', battery_hours: 30,
      bluetooth_version: '5.4', driver_mm: 30, weight_g: 250, mic: 'Beamforming array',
      connection: 'Bluetooth + 3.5mm', water_resistance: 'None', warranty_months: 12 },
  }),
  p({
    cat: 'headphones', brand: 'boAt', name: 'Airdopes 500 ANC', sku: 'SQ-AUD-0002',
    price: 1799, mrp: 4490, rating: 4.2, reviews: 11204, featured: true, stock: 210,
    tags: ['tws', 'anc', 'budget', 'gym', 'sweatproof'],
    short: 'Sweat-resistant ANC earbuds for under ₹2,000.',
    desc: 'ANC at this price is never going to be Sony-grade, but it takes the edge off a commute. IPX5 and a secure fit make these a sensible gym pair.',
    specs: { type: 'True wireless in-ear', noise_cancellation: 'Hybrid ANC 32 dB', battery_hours: 40,
      bluetooth_version: '5.3', driver_mm: 10, weight_g: 4, mic: 'Quad ENx mic',
      connection: 'Bluetooth', water_resistance: 'IPX5', warranty_months: 12 },
  }),
  p({
    cat: 'headphones', brand: 'boAt', name: 'Rockerz 550 Over-Ear', sku: 'SQ-AUD-0003',
    price: 2499, mrp: 4990, rating: 4.3, reviews: 8932, featured: false, stock: 96,
    tags: ['over ear', 'budget', 'long battery', 'wireless'],
    short: 'Big 50 mm drivers and a battery that refuses to die.',
    desc: 'No ANC, but twenty hours of playback and a comfortable clamp force. A good first pair of over-ears.',
    specs: { type: 'Over-ear', noise_cancellation: 'None', battery_hours: 20,
      bluetooth_version: '5.0', driver_mm: 50, weight_g: 245, mic: 'Single mic',
      connection: 'Bluetooth + 3.5mm', water_resistance: 'None', warranty_months: 12 },
  }),
  p({
    cat: 'headphones', brand: 'Apple', name: 'AirPods Pro 3', sku: 'SQ-AUD-0004',
    price: 24900, mrp: null, rating: 4.7, reviews: 3320, featured: false, stock: 26,
    tags: ['tws', 'anc', 'apple', 'spatial audio'],
    short: 'The obvious pick if everything else you own has an Apple logo.',
    desc: 'Transparency mode remains the best in the category, and the H3 chip cuts switching latency between devices to nearly nothing.',
    specs: { type: 'True wireless in-ear', noise_cancellation: 'Adaptive ANC', battery_hours: 30,
      bluetooth_version: '5.4', driver_mm: 11, weight_g: 5.3, mic: 'Dual beamforming',
      connection: 'Bluetooth', water_resistance: 'IP54', warranty_months: 12 },
  }),
  p({
    cat: 'headphones', brand: 'Sennheiser', name: 'Accentum Plus Wireless', sku: 'SQ-AUD-0005',
    price: 17990, mrp: 21990, rating: 4.5, reviews: 612, featured: false, stock: 11,
    tags: ['over ear', 'anc', 'audiophile', 'long battery'],
    short: 'Fifty hours of battery and a more neutral tuning than most.',
    desc: 'Sennheiser tunes these flatter than the competition, which makes them better for long listening sessions and worse for anyone who wants heavy bass.',
    specs: { type: 'Over-ear', noise_cancellation: 'Hybrid ANC', battery_hours: 50,
      bluetooth_version: '5.2', driver_mm: 37, weight_g: 227, mic: 'Dual mic',
      connection: 'Bluetooth + 3.5mm', water_resistance: 'None', warranty_months: 24 },
  }),
  p({
    cat: 'headphones', brand: 'JBL', name: 'Tune Beam 2 TWS', sku: 'SQ-AUD-0006',
    price: 5999, mrp: 8999, rating: 4.2, reviews: 2107, featured: false, stock: 74,
    tags: ['tws', 'anc', 'value', 'commute'],
    short: 'Proper ANC in the ₹6,000 bracket.',
    desc: 'The step up from budget earbuds where noise cancelling stops being a marketing bullet and starts being useful.',
    specs: { type: 'True wireless in-ear', noise_cancellation: 'Adaptive ANC', battery_hours: 40,
      bluetooth_version: '5.3', driver_mm: 10, weight_g: 5, mic: 'Quad mic',
      connection: 'Bluetooth', water_resistance: 'IP54', warranty_months: 12 },
  }),

  // -------------------------------------------------------------- monitors
  p({
    cat: 'monitors', brand: 'Dell', name: 'UltraSharp U2724D 27-inch', sku: 'SQ-MON-0001',
    price: 34990, mrp: 42990, rating: 4.7, reviews: 486, featured: true, stock: 16,
    tags: ['productivity', '1440p', 'ips', 'usb-c', 'colour accurate'],
    short: 'A 27-inch 1440p panel that is colour-accurate out of the box.',
    desc: 'Factory-calibrated to Delta E < 2, with 90 W USB-C power delivery so a laptop charges off the same cable that carries the picture.',
    specs: { display_size: 27, display_resolution: '2560 x 1440', panel_type: 'IPS Black',
      refresh_rate_hz: 120, response_time_ms: 5, brightness_nits: 400,
      ports: 'USB-C 90W, DisplayPort, HDMI, 4x USB-A', adjustable_stand: 'Height, tilt, swivel, pivot',
      warranty_months: 36 },
  }),
  p({
    cat: 'monitors', brand: 'LG', name: 'UltraGear 27GS95QE OLED', sku: 'SQ-MON-0002',
    price: 79990, mrp: 99990, rating: 4.8, reviews: 291, featured: false, stock: 8,
    tags: ['gaming', 'oled', '240hz', '1440p', 'premium'],
    short: 'OLED at 240 Hz — the fastest thing on this list.',
    desc: 'A 0.03 ms response time and per-pixel blacks. It is expensive and it is worth it if competitive gaming is the point of the desk.',
    specs: { display_size: 27, display_resolution: '2560 x 1440', panel_type: 'WOLED',
      refresh_rate_hz: 240, response_time_ms: 0.03, brightness_nits: 1300,
      ports: '2x HDMI 2.1, DisplayPort 1.4, USB-A hub', adjustable_stand: 'Height, tilt, pivot',
      warranty_months: 24 },
  }),
  p({
    cat: 'monitors', brand: 'Samsung', name: 'ViewFinity S6 34-inch Ultrawide', sku: 'SQ-MON-0003',
    price: 46990, mrp: 59990, rating: 4.4, reviews: 174, featured: false, stock: 9,
    tags: ['ultrawide', 'productivity', 'usb-c', '21:9'],
    short: 'A 21:9 ultrawide that replaces a two-monitor setup.',
    desc: 'Wide enough for a code editor and a browser side by side without the bezel down the middle. 90 W USB-C keeps the cabling to one.',
    specs: { display_size: 34, display_resolution: '3440 x 1440', panel_type: 'VA',
      refresh_rate_hz: 100, response_time_ms: 5, brightness_nits: 350,
      ports: 'USB-C 90W, 2x HDMI, DisplayPort, USB hub', adjustable_stand: 'Height, tilt',
      warranty_months: 36 },
  }),
  p({
    cat: 'monitors', brand: 'Acer', name: 'Nitro VG240Y 24-inch 180Hz', sku: 'SQ-MON-0004',
    price: 11990, mrp: 16999, rating: 4.3, reviews: 1420, featured: false, stock: 42,
    tags: ['gaming', 'budget', '1080p', '180hz'],
    short: '180 Hz for under ₹12,000.',
    desc: 'The cheapest sensible gaming monitor. 1080p on a 24-inch panel is the right pixel density, and 180 Hz is well past the point of diminishing returns.',
    specs: { display_size: 23.8, display_resolution: '1920 x 1080', panel_type: 'IPS',
      refresh_rate_hz: 180, response_time_ms: 1, brightness_nits: 250,
      ports: '2x HDMI 2.0, DisplayPort 1.2, 3.5mm', adjustable_stand: 'Tilt only',
      warranty_months: 36 },
  }),

  // ------------------------------------------------------------- keyboards
  p({
    cat: 'keyboards', brand: 'Keychron', name: 'K8 Pro Wireless Mechanical', sku: 'SQ-KBD-0001',
    price: 11999, mrp: 14999, rating: 4.7, reviews: 934, featured: true, stock: 23,
    tags: ['mechanical', 'wireless', 'hot swappable', 'tenkeyless', 'mac'],
    short: 'Hot-swappable, wireless, and works properly on macOS.',
    desc: 'The K8 Pro is the default recommendation for a first mechanical keyboard: tenkeyless, hot-swappable so you can change switches without soldering, and a Mac layout that is not an afterthought.',
    specs: { layout: 'Tenkeyless (87-key)', switch_type: 'Gateron G Pro Brown', connection: 'Bluetooth 5.1 + USB-C',
      backlight: 'RGB', hot_swappable: 'Yes', battery_hours: 100, weight_g: 810,
      compatibility: 'Windows, macOS, Linux', warranty_months: 12 },
  }),
  p({
    cat: 'keyboards', brand: 'Logitech', name: 'MX Keys S Wireless', sku: 'SQ-KBD-0002',
    price: 11495, mrp: 13995, rating: 4.6, reviews: 2211, featured: false, stock: 31,
    tags: ['office', 'wireless', 'low profile', 'multi device', 'quiet'],
    short: 'The quiet, low-profile board for people who type all day.',
    desc: 'Scissor switches with a spherically dished keycap. Pairs with three devices and switches between them with a keypress.',
    specs: { layout: 'Full size', switch_type: 'Scissor (low profile)', connection: 'Bluetooth + Logi Bolt',
      backlight: 'Smart backlight', hot_swappable: 'No', battery_hours: 240, weight_g: 810,
      compatibility: 'Windows, macOS, Linux, iOS, Android', warranty_months: 12 },
  }),
  p({
    cat: 'keyboards', brand: 'Razer', name: 'Huntsman V3 Pro TKL', sku: 'SQ-KBD-0003',
    price: 21999, mrp: 25999, rating: 4.5, reviews: 418, featured: false, stock: 7,
    tags: ['gaming', 'optical', 'rapid trigger', 'tenkeyless', 'esports'],
    short: 'Adjustable actuation and rapid trigger for competitive play.',
    desc: 'Analogue optical switches let you set the actuation point per key, and rapid trigger resets on the way up. This is a competitive-shooter keyboard first.',
    specs: { layout: 'Tenkeyless (87-key)', switch_type: 'Razer Analog Optical Gen-2', connection: 'USB-C wired',
      backlight: 'Per-key RGB', hot_swappable: 'No', polling_rate_hz: 8000, weight_g: 900,
      compatibility: 'Windows, macOS', warranty_months: 24 },
  }),
  p({
    cat: 'keyboards', brand: 'Zebronics', name: 'Max Plus Mechanical 104-key', sku: 'SQ-KBD-0004',
    price: 2499, mrp: 3999, rating: 4.0, reviews: 3702, featured: false, stock: 118,
    tags: ['budget', 'mechanical', 'wired', 'full size', 'rgb'],
    short: 'A real mechanical keyboard for the price of a membrane one.',
    desc: 'Outemu Blue switches, a full-size layout and RGB. Build quality is what you expect at ₹2,500, but the typing feel is genuinely mechanical.',
    specs: { layout: 'Full size (104-key)', switch_type: 'Outemu Blue', connection: 'USB-A wired',
      backlight: 'RGB', hot_swappable: 'No', weight_g: 1050, compatibility: 'Windows, Linux',
      warranty_months: 12 },
  }),

    // ------------------------------------------------------------------ mice
  p({
    cat: 'mice', brand: 'Logitech', name: 'MX Master 3S', sku: 'SQ-MSE-0001',
    price: 8495, mrp: 10995, rating: 4.8, reviews: 4110, featured: true, stock: 38,
    tags: ['productivity', 'wireless', 'ergonomic', 'quiet', 'multi device'],
    short: 'The productivity mouse everything else is measured against.',
    desc: 'The MagSpeed scroll wheel free-spins through a thousand lines in a second, and the 8000 DPI sensor tracks on glass. Quiet clicks are the 3S upgrade.',
    specs: { sensor_dpi: 8000, buttons: 7, connection: 'Bluetooth + Logi Bolt', weight_g: 141,
      battery_hours: 1680, polling_rate_hz: 125, compatibility: 'Windows, macOS, Linux, iPadOS',
      warranty_months: 12 },
  }),
  p({
    cat: 'mice', brand: 'Razer', name: 'DeathAdder V3 Pro', sku: 'SQ-MSE-0002',
    price: 13999, mrp: 16999, rating: 4.7, reviews: 892, featured: false, stock: 14,
    tags: ['gaming', 'wireless', 'lightweight', 'esports', 'ergonomic'],
    short: '63 g wireless with a 30K sensor.',
    desc: 'The shape is the reason people keep buying DeathAdders. The V3 Pro drops it to 63 g without hollowing out the shell.',
    specs: { sensor_dpi: 30000, buttons: 6, connection: 'HyperSpeed Wireless + USB-C', weight_g: 63,
      battery_hours: 90, polling_rate_hz: 1000, compatibility: 'Windows, macOS', warranty_months: 24 },
  }),
  p({
    cat: 'mice', brand: 'Logitech', name: 'G502 X Lightspeed', sku: 'SQ-MSE-0003',
    price: 12995, mrp: 15995, rating: 4.6, reviews: 1533, featured: false, stock: 21,
    tags: ['gaming', 'wireless', 'many buttons', 'mmo', 'customisable'],
    short: 'Thirteen programmable buttons and a wheel that unlocks.',
    desc: 'For anyone who wants macros bound to the mouse. Heavier than an esports mouse, deliberately.',
    specs: { sensor_dpi: 25600, buttons: 13, connection: 'Lightspeed Wireless + USB-C', weight_g: 102,
      battery_hours: 140, polling_rate_hz: 1000, compatibility: 'Windows, macOS', warranty_months: 24 },
  }),
  p({
    cat: 'mice', brand: 'HP', name: 'Wireless Silent Mouse 280M', sku: 'SQ-MSE-0004',
    price: 999, mrp: 1699, rating: 4.1, reviews: 5620, featured: false, stock: 240,
    tags: ['budget', 'wireless', 'quiet', 'office', 'travel'],
    short: 'Silent clicks and an eighteen-month battery, for ₹999.',
    desc: 'Nothing clever here — it is a quiet, small, reliable wireless mouse for a laptop bag.',
    specs: { sensor_dpi: 1600, buttons: 3, connection: '2.4 GHz USB receiver', weight_g: 68,
      battery_hours: 13000, polling_rate_hz: 125, compatibility: 'Windows, macOS, Linux',
      warranty_months: 12 },
  }),

  // ----------------------------------------------------------- controllers
  p({
    cat: 'controllers', brand: 'Sony', name: 'DualSense Edge Wireless', sku: 'SQ-CTL-0001',
    price: 19990, mrp: 22990, rating: 4.6, reviews: 344, featured: false, stock: 10,
    tags: ['pro controller', 'playstation', 'pc', 'haptics', 'swappable sticks'],
    short: 'Swappable stick modules and back paddles.',
    desc: 'The stick modules are replaceable, which matters because stick drift is what kills every other controller. Expensive, but it outlives them.',
    specs: { connection: 'Bluetooth + USB-C', battery_hours: 6, weight_g: 325,
      compatibility: 'PlayStation 5, PC', haptics: 'Adaptive triggers + haptic feedback',
      buttons: 20, warranty_months: 12 },
  }),
  p({
    cat: 'controllers', brand: 'Microsoft', name: 'Xbox Wireless Controller', sku: 'SQ-CTL-0002',
    price: 5490, mrp: 6490, rating: 4.7, reviews: 6208, featured: true, stock: 47,
    tags: ['xbox', 'pc', 'bluetooth', 'default pick', 'value'],
    short: 'The controller PC games are designed around.',
    desc: 'If a PC game supports a gamepad, it supports this one with no configuration. Runs on AA batteries, which is either the best or worst feature depending on who you ask.',
    specs: { connection: 'Bluetooth + USB-C + Xbox Wireless', battery_hours: 40, weight_g: 287,
      compatibility: 'Xbox, PC, Android, iOS', haptics: 'Impulse triggers', buttons: 17,
      warranty_months: 12 },
  }),
  p({
    cat: 'controllers', brand: 'GameSir', name: 'G8 Plus Mobile Gamepad', sku: 'SQ-CTL-0003',
    price: 6499, mrp: 7999, rating: 4.4, reviews: 517, featured: false, stock: 18,
    tags: ['mobile gaming', 'telescopic', 'hall effect', 'cloud gaming'],
    short: 'Hall-effect sticks that clamp around a phone.',
    desc: 'Hall-effect sensors mean no stick drift, ever. Built for cloud gaming and emulators on a phone.',
    specs: { connection: 'Bluetooth 5.3 + USB-C', battery_hours: 15, weight_g: 232,
      compatibility: 'Android, iOS, Switch, PC', haptics: 'Dual motor', buttons: 16,
      warranty_months: 12 },
  }),

  // -------------------------------------------------------- gaming headsets
  p({
    cat: 'gaming-headsets', brand: 'SteelSeries', name: 'Arctis Nova 7 Wireless', sku: 'SQ-GHS-0001',
    price: 17999, mrp: 20999, rating: 4.6, reviews: 728, featured: true, stock: 15,
    tags: ['gaming', 'wireless', 'low latency', 'comfortable', 'multiplatform'],
    short: 'Simultaneous 2.4 GHz and Bluetooth — game audio and a call at once.',
    desc: 'The dual-wireless trick is genuinely useful: game audio over the low-latency dongle, Discord or a phone call over Bluetooth, both in your ears at the same time.',
    specs: { type: 'Over-ear', noise_cancellation: 'Passive isolation', battery_hours: 38,
      bluetooth_version: '5.0', driver_mm: 40, weight_g: 325, mic: 'Retractable ClearCast Gen 2',
      connection: '2.4 GHz + Bluetooth + USB-C', compatibility: 'PC, PS5, Switch, mobile',
      warranty_months: 12 },
  }),
  p({
    cat: 'gaming-headsets', brand: 'HyperX', name: 'Cloud III Wired', sku: 'SQ-GHS-0002',
    price: 7990, mrp: 9990, rating: 4.5, reviews: 1904, featured: false, stock: 34,
    tags: ['gaming', 'wired', 'comfortable', 'value', 'memory foam'],
    short: 'The comfort benchmark, and it is still wired.',
    desc: 'Memory foam and a light clamp mean these disappear after an hour. Wired means no battery to charge and no latency to argue about.',
    specs: { type: 'Over-ear', noise_cancellation: 'Passive isolation', driver_mm: 53, weight_g: 320,
      mic: 'Detachable 10mm cardioid', connection: '3.5mm + USB-C',
      compatibility: 'PC, PS5, Xbox, Switch, mobile', warranty_months: 24 },
  }),
  p({
    cat: 'gaming-headsets', brand: 'Logitech', name: 'G335 Wired Gaming Headset', sku: 'SQ-GHS-0003',
    price: 4495, mrp: 6495, rating: 4.2, reviews: 2381, featured: false, stock: 2,
    tags: ['gaming', 'wired', 'budget', 'lightweight', 'entry level'],
    short: '240 g, so it does not press down after two hours.',
    desc: 'The lightest headset here. A suspension band spreads the weight, which is the whole reason to pick it over similarly priced rivals.',
    specs: { type: 'Over-ear', noise_cancellation: 'Passive isolation', driver_mm: 40, weight_g: 240,
      mic: 'Flip-to-mute boom', connection: '3.5mm', compatibility: 'PC, PS5, Xbox, Switch, mobile',
      warranty_months: 24 },
  }),

  // ----------------------------------------------------- gaming accessories
  p({
    cat: 'gaming-accessories', brand: 'ASUS', name: 'ROG 65W GaN Charger', sku: 'SQ-GAC-0001',
    price: 2899, mrp: 3499, rating: 4.6, reviews: 540, featured: false, stock: 88,
    tags: ['charger', 'gan', 'usb-c', 'travel', 'compact'],
    short: 'A 65 W charger the size of a matchbox.',
    desc: 'GaN means the same power output in about a third of the volume of an old brick. Charges a laptop, a phone and a controller off one plug.',
    specs: { power_w: 65, connection: 'USB-C PD 3.0 + USB-A', weight_g: 112,
      dimensions_cm: '5.5 x 5.2 x 3.0', compatibility: 'Laptops, phones, tablets, controllers',
      warranty_months: 12 },
  }),
  p({
    cat: 'gaming-accessories', brand: 'Cosmic Byte', name: 'XL Desk Mousepad 900x400', sku: 'SQ-GAC-0002',
    price: 799, mrp: 1499, rating: 4.4, reviews: 4620, featured: false, stock: 156,
    tags: ['mousepad', 'desk mat', 'xl', 'stitched edge', 'budget'],
    short: 'A desk mat that covers the keyboard and the mouse.',
    desc: 'Stitched edges so it does not fray, and a rubber base that stays put. 900 x 400 mm covers a standard desk.',
    specs: { material: 'Micro-woven cloth over natural rubber', dimensions_cm: '90 x 40 x 0.4',
      weight_g: 640, water_resistance: 'Water-repellent coating', warranty_months: 6 },
  }),
  p({
    cat: 'gaming-accessories', brand: 'Anker', name: '7-in-1 USB-C Docking Hub', sku: 'SQ-GAC-0003',
    price: 4299, mrp: 5999, rating: 4.5, reviews: 1873, featured: false, stock: 51,
    tags: ['hub', 'usb-c', 'hdmi', 'docking', 'laptop'],
    short: 'Turns one USB-C port into seven.',
    desc: 'HDMI at 4K60, 100 W passthrough charging, SD and microSD, and three USB-A ports. The passthrough is the part cheap hubs get wrong.',
    specs: { ports: 'HDMI 4K60, 3x USB-A 3.0, USB-C PD 100W, SD, microSD',
      connection: 'USB-C', weight_g: 68, dimensions_cm: '11.5 x 3.2 x 1.5',
      compatibility: 'Windows, macOS, Linux, iPad', warranty_months: 18 },
  }),

  // ----------------------------------------------------------------- shoes
  p({
    cat: 'shoes', brand: 'Nike', name: 'Pegasus 41 Running Shoes', sku: 'SQ-SHO-0001',
    price: 10795, mrp: 12995, rating: 4.6, reviews: 1841, featured: true, stock: 44,
    tags: ['running', 'daily trainer', 'cushioned', 'neutral'],
    short: 'The default daily trainer, in its forty-first year.',
    desc: 'ReactX foam with two Air Zoom units. Neutral, cushioned, and durable enough for six hundred kilometres — the shoe you buy when you just want to run.',
    specs: { material: 'Engineered mesh upper', sole: 'ReactX foam with Air Zoom', closure: 'Lace-up',
      weight_g: 286, use_case: 'Daily road running', sizes: 'UK 6-12', colour: 'Black / White',
      warranty_months: 3 },
  }),
  p({
    cat: 'shoes', brand: 'Adidas', name: 'Ultraboost Light', sku: 'SQ-SHO-0002',
    price: 13999, mrp: 18999, rating: 4.5, reviews: 1203, featured: false, stock: 27,
    tags: ['running', 'lifestyle', 'boost', 'comfortable', 'everyday'],
    short: 'More comfortable than fast, and it knows it.',
    desc: 'Light Boost foam is thirty percent lighter than the original. It has drifted from a race shoe into an all-day comfort shoe, which is what most people wanted anyway.',
    specs: { material: 'Primeknit+ upper', sole: 'Light Boost midsole, Continental rubber',
      closure: 'Lace-up', weight_g: 299, use_case: 'Everyday and easy runs', sizes: 'UK 6-12',
      colour: 'Core Black', warranty_months: 3 },
  }),
  p({
    cat: 'shoes', brand: 'Puma', name: 'Softride Pro Trainer', sku: 'SQ-SHO-0003',
    price: 5499, mrp: 7999, rating: 4.2, reviews: 892, featured: false, stock: 63,
    tags: ['training', 'gym', 'stable', 'value'],
    short: 'A flat, stable base for lifting and gym work.',
    desc: 'Running shoes are the wrong shape for a squat rack. This has a firmer, flatter midsole and a wider heel.',
    specs: { material: 'Mesh and synthetic overlay', sole: 'Softride EVA, flat profile',
      closure: 'Lace-up', weight_g: 315, use_case: 'Gym training and lifting', sizes: 'UK 6-11',
      colour: 'Grey / Orange', warranty_months: 3 },
  }),
  p({
    cat: 'shoes', brand: 'Campus', name: 'Everyday Sneaker', sku: 'SQ-SHO-0004',
    price: 1799, mrp: 2999, rating: 4.0, reviews: 7204, featured: false, stock: 190,
    tags: ['casual', 'budget', 'everyday', 'lightweight'],
    short: 'A ₹1,800 sneaker that does not look like one.',
    desc: 'Lightweight, plain, and it goes with everything. Not a running shoe, despite the styling.',
    specs: { material: 'Synthetic mesh', sole: 'EVA', closure: 'Lace-up', weight_g: 260,
      use_case: 'Casual everyday wear', sizes: 'UK 6-11', colour: 'White', warranty_months: 3 },
  }),

  // -------------------------------------------------------------- t-shirts
  p({
    cat: 't-shirts', brand: 'Uniqlo', name: 'Supima Cotton Crew Neck Tee', sku: 'SQ-TSH-0001',
    price: 1490, mrp: 1990, rating: 4.6, reviews: 3312, featured: false, stock: 210,
    tags: ['cotton', 'basic', 'everyday', 'crew neck'],
    short: 'The plain white tee, done properly.',
    desc: 'Supima cotton holds its shape through far more washes than standard cotton. This is a basic that stays looking new.',
    specs: { material: '100% Supima cotton', fit: 'Regular', gsm: 180, sleeve: 'Short',
      care: 'Machine wash cold, tumble dry low', sizes: 'XS-XXL', colour: 'White' },
  }),
  p({
    cat: 't-shirts', brand: 'Nike', name: 'Dri-FIT Training Tee', sku: 'SQ-TSH-0002',
    price: 1795, mrp: 2295, rating: 4.4, reviews: 2108, featured: false, stock: 148,
    tags: ['gym', 'moisture wicking', 'training', 'polyester'],
    short: 'Moves sweat off the skin instead of holding it.',
    desc: 'Dri-FIT polyester dries in a fraction of the time cotton takes. For anything where you will sweat, this is the right fabric.',
    specs: { material: '100% recycled polyester', fit: 'Athletic', gsm: 140, sleeve: 'Short',
      care: 'Machine wash cold, do not use fabric softener', sizes: 'S-XXL', colour: 'Black' },
  }),
  p({
    cat: 't-shirts', brand: 'H&M', name: 'Oversized Heavyweight Tee', sku: 'SQ-TSH-0003',
    price: 999, mrp: 1499, rating: 4.1, reviews: 4407, featured: false, stock: 176,
    tags: ['oversized', 'heavyweight', 'streetwear', 'budget'],
    short: '240 GSM, so it hangs rather than clings.',
    desc: 'The heavier fabric is what makes an oversized cut work. At 240 GSM this drapes properly instead of looking like a shirt that is simply too big.',
    specs: { material: '100% organic cotton', fit: 'Oversized', gsm: 240, sleeve: 'Short drop-shoulder',
      care: 'Machine wash cold', sizes: 'XS-XL', colour: 'Sand' },
  }),

  // --------------------------------------------------------------- jackets
  p({
    cat: 'jackets', brand: 'Decathlon', name: 'Quechua MH500 Windproof Jacket', sku: 'SQ-JKT-0001',
    price: 3499, mrp: 4999, rating: 4.5, reviews: 1642, featured: false, stock: 58,
    tags: ['windproof', 'hiking', 'packable', 'lightweight'],
    short: 'Packs into its own pocket and blocks real wind.',
    desc: 'Not waterproof — windproof, which is the more useful property most of the year. Packs down to the size of a water bottle.',
    specs: { material: 'Ripstop polyester', insulation: 'None (shell)', water_resistance: 'DWR coating, not waterproof',
      pockets: '2 zip hand, 1 chest', fit: 'Regular', weight_g: 240, sizes: 'S-XXL', colour: 'Navy' },
  }),
  p({
    cat: 'jackets', brand: 'Uniqlo', name: 'Ultra Light Down Jacket', sku: 'SQ-JKT-0002',
    price: 5990, mrp: 7990, rating: 4.7, reviews: 2871, featured: true, stock: 36,
    tags: ['down', 'packable', 'winter', 'lightweight', 'travel'],
    short: '235 g of down that folds into a bag the size of a paperback.',
    desc: 'Genuine down at a fraction of the weight of a fleece with the same warmth. The packability makes it a travel staple.',
    specs: { material: 'Nylon shell', insulation: '750 fill power down', water_resistance: 'Water-repellent finish',
      pockets: '2 zip hand', fit: 'Slim', weight_g: 235, sizes: 'XS-XXL', colour: 'Olive' },
  }),
  p({
    cat: 'jackets', brand: 'Levi\'s', name: 'Sherpa Trucker Jacket', sku: 'SQ-JKT-0003',
    price: 7999, mrp: 10999, rating: 4.4, reviews: 986, featured: false, stock: 21,
    tags: ['denim', 'sherpa', 'winter', 'classic', 'lined'],
    short: 'The trucker jacket, lined for actual winter.',
    desc: 'Sherpa lining turns a three-season denim jacket into something that works below ten degrees.',
    specs: { material: 'Cotton denim with sherpa lining', insulation: 'Sherpa fleece',
      water_resistance: 'None', pockets: '2 chest flap, 2 hand', fit: 'Regular', weight_g: 980,
      sizes: 'S-XXL', colour: 'Mid Wash Indigo' },
  }),

  // ------------------------------------------------------------------ bags
  p({
    cat: 'bags', brand: 'Wildcraft', name: 'Trident 35L Laptop Backpack', sku: 'SQ-BAG-0001',
    price: 2699, mrp: 3999, rating: 4.4, reviews: 5230, featured: false, stock: 92,
    tags: ['backpack', 'laptop', 'commute', 'water resistant', 'value'],
    short: '35 litres with a padded 16-inch laptop sleeve.',
    desc: 'Enough volume for a laptop, a gym change and a lunch box. The rain cover tucks into the base, which matters in monsoon.',
    specs: { capacity_l: 35, material: '600D polyester', laptop_fit_inch: 16,
      water_resistance: 'Water-resistant with rain cover', weight_kg: 0.85, compartments: 3,
      colour: 'Black', warranty_months: 12 },
  }),
  p({
    cat: 'bags', brand: 'Lenovo', name: 'Laptop Sleeve 14-inch', sku: 'SQ-BAG-0002',
    price: 899, mrp: 1499, rating: 4.1, reviews: 2214, featured: false, stock: 134,
    tags: ['sleeve', 'laptop', 'minimal', 'budget', 'protective'],
    short: 'A padded sleeve, and nothing else.',
    desc: 'For when the laptop goes inside a bag that has no padding of its own. Water-resistant shell, soft lining.',
    specs: { material: 'Neoprene with polyester shell', laptop_fit_inch: 14,
      water_resistance: 'Water-resistant', weight_kg: 0.19, compartments: 1,
      dimensions_cm: '35 x 25 x 2', colour: 'Grey', warranty_months: 12 },
  }),
  p({
    cat: 'bags', brand: 'American Tourister', name: 'Zork Sling Crossbody', sku: 'SQ-BAG-0003',
    price: 1299, mrp: 1999, rating: 4.2, reviews: 3108, featured: false, stock: 76,
    tags: ['sling', 'crossbody', 'everyday carry', 'compact'],
    short: 'Phone, wallet, charger, earbuds — and nothing more.',
    desc: 'A sling for days when a backpack is too much. Fits a tablet at a push.',
    specs: { capacity_l: 5, material: 'Polyester', water_resistance: 'Water-resistant',
      weight_kg: 0.3, compartments: 3, dimensions_cm: '30 x 18 x 8', colour: 'Charcoal',
      warranty_months: 12 },
  }),

  // ------------------------------------------------------- home accessories
  p({
    cat: 'home-accessories', brand: 'Xiaomi', name: 'Mi LED Desk Lamp 1S', sku: 'SQ-HOM-0001',
    price: 2999, mrp: 3999, rating: 4.5, reviews: 4118, featured: false, stock: 67,
    tags: ['desk lamp', 'adjustable', 'eye care', 'work from home'],
    short: 'Adjustable colour temperature, flicker-free.',
    desc: 'Four lighting modes and stepless brightness. Flicker-free is the specification that actually matters for long evenings at a desk.',
    specs: { power_w: 9, colour: 'White', dimensions_cm: '15 x 15 x 45',
      material: 'Aluminium and ABS', compatibility: 'App and voice control',
      warranty_months: 12 },
  }),
  p({
    cat: 'home-accessories', brand: 'Milton', name: 'Thermosteel Flask 1000 ml', sku: 'SQ-HOM-0002',
    price: 1449, mrp: 1899, rating: 4.6, reviews: 8902, featured: false, stock: 143,
    tags: ['flask', 'insulated', 'steel', 'travel', 'everyday'],
    short: 'Twenty-four hours cold, twelve hours hot.',
    desc: 'Double-walled stainless steel with a vacuum between the layers. The lid seals properly, which is where cheaper flasks fail.',
    specs: { capacity_ml: 1000, material: '18/8 stainless steel', weight_g: 520,
      dimensions_cm: '8 x 8 x 31', water_resistance: 'Leak-proof lid', warranty_months: 12 },
  }),
  p({
    cat: 'home-accessories', brand: 'Anker', name: 'PowerCore 20000 PD Power Bank', sku: 'SQ-HOM-0003',
    price: 4499, mrp: 5999, rating: 4.7, reviews: 6314, featured: true, stock: 58,
    tags: ['power bank', 'usb-c', 'fast charging', 'travel', 'laptop charging'],
    short: '20,000 mAh with enough output to charge a laptop.',
    desc: '65 W USB-C output means this charges a MacBook Air, not just a phone. Four full phone charges from one fill.',
    specs: { capacity_ml: null, battery_mah: 20000, power_w: 65, connection: 'USB-C PD + 2x USB-A',
      weight_g: 494, dimensions_cm: '16 x 6 x 2.7',
      compatibility: 'Laptops, phones, tablets, consoles', warranty_months: 18 },
  }),
];
